### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by lukejpreston** [chtefi/react-line#1]
I do something like:

```
import Line from 'react-line'

...

<Line
    from={{x: 10, y: 20}}
    to={{x: 10, y: 100}}
    style='5px solid orange' />
...
```

and get

> Uncaught Error: Cannot find module "react-line"

Am I doing something wrong? Your docs do not say how you should bring this in if that helps...

**Comment by redixhumayun** [comment]
Have a similar issue, where I am getting the following error
Error in ./~/react-line/index.js
Module parse failed: /Users/zaidhumayun/Desktop/React/pokedashboard/node_modules/react-line/index.js Unexpected token (5:19)

Don't know what's going on.

**Comment by marceloogeda** [comment]
It didn't work because it is a native ES2015 module, cannot be consumed without transpilation (at this moment)

**Comment by lukejpreston** [comment]
I don't use this library anymore but could you use something like browserify and babel (or webpack) and create a `dist` folder?

**Comment by hsh2001** [comment]
Use [`react-stroke-line`](https://www.npmjs.com/package/react-stroke-line)!
