### ISSUE TITLE
Lines not workingin viewport

### ISSUE THREAD

**Issue by gate2017aloy** [chtefi/react-line#2]
I have two draggable divs. I am connecting them using LIne. Within the viewport if I drag the divs the line stretches  accordingly and it works completely fine

<img width="1680" alt="initial position" src="https://user-images.githubusercontent.com/29536502/56558543-b10a2580-65bc-11e9-9569-4ffb97809dac.png">
<img width="1680" alt="inside viewport" src="https://user-images.githubusercontent.com/29536502/56558544-b10a2580-65bc-11e9-9449-4178c370229b.png">
<img width="1680" alt="outside viewport" src="https://user-images.githubusercontent.com/29536502/56558546-b1a2bc00-65bc-11e9-9d02-9ae89f73f4ec.png">

 . But when I drag the divs out of viewport(scroll bar comes up automatically) the lines don't work. They stay within the viewport.

**Comment by sderosiaux** [comment]
Hey @gate2017aloy, it's an issue with the mouse handlers you have set, not related to react-line itself (it deals only with the drawing part). I don't know if there is a way to "catch" the mouse-move outside of the viewport.

**Comment by gate2017aloy** [comment]
Hi @sderosiaux the issue is resolved. Thanks for the reply. Only had to add the pageOffsetX and pageOffsetY
